### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ErwanGalline** [input-output-hk/plutus-prototype#9]
Hey,

I 'm new with Haskell techno stack.
Do you think it's possible to add few build instructions in readme file than can help me to run 'cabal repl' command ?
Currently I have : 
```
$ cabal repl 
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring plutus-prototype-0.1.0.0...
cabal: At least the following dependencies are missing:
cardano-crypto -any
```

Even if previous 'stack install' did fetch and build cardano-crypto dependency, build and cache plutus-prototype (with couple of warnings :)).
I am testing master branch.

Thanks for your help

**Comment by neongreen** [comment]
Have you tried `stack repl`?

**Comment by ErwanGalline** [comment]
@neongreen It works,  thanks to you !

**Comment by vantuz-subhuman** [comment]
@neongreen, thank you! This works for MacOS

**Comment by vmchale** [comment]
If you'd like to work with `cabal` for any reason, I recommend `cabal new-repl` :)
