### ISSUE TITLE
Plutus-core overflows for values allowed by the specification

### ISSUE THREAD

**Issue by nishantjr** [input-output-hk/plutus-prototype#96]
The spec allows integers with size 1 as large as 127, but the reference implementation overflows at just 4.

```
$ cat overflow.plc
(program 0.1.0 (con 1 ! 4))
$ cat overflow.plc | language-plutus-core-run-ck
Integer overflow at 1:21.
```

**Comment by effectfully** [comment]
I fixed this a while ago. You're using an old executable. Now the correct command is

```
echo "(program 0.1.0 [(lam x [(con integer) (con 2)] x) (con 2 ! 4)])" | plc evaluate --stdin
```

We updated the [README](https://github.com/input-output-hk/plutus-prototype/tree/master/language-plutus-core), but we also should have warned you about the changes. Sorry about that.

Please confirm `plc evaluate --stdin` works correctly and I'll close this.

**Comment by lucaspena** [comment]
Yes, sorry, thanks for the update. We were still using `language-plutus-core-run-ck`. It all works now.

**Comment by effectfully** [comment]
Cool.
